name: pingpong

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building on Windows 11 x64...
    runs-on: windows-11-arm
    timeout-minutes: 360
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Environment
        run: |
          # Desativa a tela de configuração inicial (OOBE) de forma robusta
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE" /v SkipMachineOOBE /t REG_DWORD /d 1 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE" /v BypassNRO /t REG_DWORD /d 1 /f
          # Verifica e cria o diretório C:\actions-runner no PowerShell
          if (-not (Test-Path "C:\actions-runner")) { New-Item -Path "C:\actions-runner" -ItemType Directory -Force }
          # Configura o RunOnce para executar o setup após o boot
          reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce" /v SetupScript /t REG_SZ /d "cmd /c C:\actions-runner\setup.bat" /f
          # Cria o arquivo setup.bat
          echo @echo off > C:\actions-runner\setup.bat
          echo call Downloads.bat >> C:\actions-runner\setup.bat
          echo exit >> C:\actions-runner\setup.bat

      - name: Downloading & Installing Essentials
        run: cmd /c Downloads.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
