name: PingPong

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-11
    timeout-minutes: 360
    
    steps:
      - name: Baixando e Esperando o Robô Reagir
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/gusta7w7/pcrdp-avica/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
